### ISSUE TITLE
Schematics?

### ISSUE THREAD

**Issue by andreacampanella** [zeldin/super-reu#1]
would be nice to have an idea of the hardware requirement and schematics to facilitate the port to different FPGAs platforms

**Comment by zeldin** [comment]
The schematics of the Chameleon v2 are available here:
http://wiki.icomp.de/w/images/8/88/Chameleon_schematics_v2.pdf
But of course not everything on there is needed by super-reu.
I'll try to make a writeup of the requirements on a new hardware platform.  Thanks for the suggestion!
